### PR TITLE
feat: Add support for null and undefined values

### LINKED ISSUE #146: Breaks when using null or undefined values
It'd be good to support these values.

Error

`TypeError: Cannot read property 'generatorType' of null`

Stacktrace:

```
 at isGenerator (node_modules/@jackfranklin/test-data-bot/src/index.ts:62:36)
 at expandConfigField (node_modules/@jackfranklin/test-data-bot/src/index.ts:103:9)
 at node_modules/@jackfranklin/test-data-bot/src/index.ts:90:16
```

Is this on purpose? Otherwise, let me know I can open a PR to fix it.

### PR DESCRIPTION
**Pull request by r-inaldi**
Sometimes I need the object structure to be defined but with no values.

Fixes #146

### CODE REVIEW

**Comment by ironosity** [comment]
Is there a reason this isn't being accepted @jackfranklin ?  This is causing me to make ugly builders. Workaround doesn't work if you use builders within builders

**Comment by jackfranklin** [comment]
Hey sorry for my slow replies here.

I'm confused here because if I have an interface of `{ age: number }`, then `{ age: undefined }` isn't valid, I don't think? [At least based on this](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkEFwDmEAXMiAK4C2ARtLgL64ID2I6YyAHhRlgC8OZCXLIqIACYQYoCFOQtcQA). [And the same is true for `null`](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkEFwDmEAXMiAK4C2ARtLgL64ID2I6YyAHhRlgC8OZCXKUqAG0nIWuIA). So I'm not sure what the problem is here or what you're trying to solve. Could you please clarify what issues you're seeing ?

I'll be quicker on the replies next time!

**Comment by r-inaldi** [comment]
I cannot say about declaring interfaces because I use it with vanilla JS. The most important part for me is this `return (field as FieldGenerator)?.generatorType !== undefined;`, since I want to use with null or undefined values.

**Comment by jackfranklin** [comment]
So your problem right now is that test-data-bot doesn't let you pass:

```
{ fields: { age: null } }
```

And that sometimes in tests you want to be able to pass the literal value `null` ?

I think as a work around you could use `{ fields: { age: perBuild(() => null) } }` but I agree that's not nice. Maybe we support `{ age: literal(null) }` instead? That might be cleaner.

**Comment by ironosity** [comment]
and the workaround doesn't work if you use builders to generate field in
other builders. Then the error comes back. :(
Eric Merrill

**Comment by jackfranklin** [comment]
@ironosity please could you share an example? Just to make sure I fully understand so we can figure out a solution :)

**Comment by ironosity** [comment]
Sure, I have a builder that looks like this. 
`const companyBuilder = build('Company', {
  fields: {
    id: 'Q29tcGFueTozCg==',
    name: 'Divvy // Main',
    mailingAddress: addressBuilder(),
    billingAddress: addressBuilder()
  }`

and then if addressBuilder has any nulls it will fail:
`  fields: {
    street1: fake(f => f.address.streetAddress()),
    street2: perBuild(() => null),
    city: fake(f => f.address.city()),
    state: fake(f => f.address.state()),
    zipCode: fake(f => f.address.zipCode())
  }
})`

**Comment by r-inaldi** [comment]
I think string and number literals work doesn't they? Why the different treatment for null and undefined values? Just trying to understand the reason behind the `literal()`.

**Comment by jackfranklin** [comment]
> Just trying to understand the reason behind literal().

I'm wondering (not convinced) if it's cleaner to say that every `field` _must_ be a builder of some description so we can easily check (e.g. if we find a field with `literal('x')` we know to just blat it out). That might be easier than trying to figure out what the field is. Although it makes overriding and creating builders with static literal values more boilerplate-y so I'm not sure I love that.

Thinking about it this PR might be enough if we update the TypeScript types in the test file that you created. @r-inaldi.

@ironosity I'm going to use your example as a test case in the codebase when we fix this to ensure it's fixed properly.

**Comment by r-inaldi** [comment]
Sure! Can you tell me which type specifically?

**Comment by jackfranklin** [comment]
@r-inaldi I took your work and tweaked it a little in #162, would you mind having a look? Let's move the conversation there 👍  Thanks for your hard work getting us to this part!

**Pull request closed without merging**
